######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 18 19:58:33 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
RESOURCES += Resources.qrc
