######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 21 13:21:33 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h \
    config.h
SOURCES += dialog.cpp main.cpp
RESOURCES += Resources.qrc
